/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * FrmCategoria.java
 *
 * Created on 13/08/2010, 03:11:46 PM
 */
package ComponentePresentacion;

import ComponenteClase.Categoria;
import ComponenteDatos.BDCategoria;
import ComponenteOtros.metodos;
import ComponenteOtros.mipanel;
import java.awt.Toolkit;
import java.net.MalformedURLException;
import java.net.URL;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.UIManager;

/**
 *
 * @author RicharDK!!
 */
public class FrmCategoria extends javax.swing.JFrame {

    /** Creates new form FrmCategoria */
    public FrmCategoria() {
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
    }
    metodos met = new metodos() {
    };
    String ImagenURL;

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    public void Mostrar(JPanel p) {
        try {
            //se asigna a "url" el archivo de imagen seleccionado
            URL url = met.getObtener();
            //se lo coloca en memoria
            met.cargar_imagen(url);
            //se aÃ±ade al contenedor
            p.add(new mipanel(met.Obtener_imagen_de_Buffer(), p.getSize()) {
            });
            p.setVisible(true);
            p.repaint();
        } catch (Exception ex) {
            Logger.getLogger(metodos.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
    /*
     * A continuacion implementaremos el Método Buscar Categoria
     */

    public void BuscarCategoria() {
        Categoria cat = null;
        try {
            cat = BDCategoria.buscarCategoriaNomCM(txtnombreCat.getText());
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "ERROR:" + e.getMessage());
        }
        if (cat != null) {
            try {
                txtnombreCat.setText(cat.getNomcateg());
                URL url = new URL(cat.getImagen());
                met.setObtener(url);
                met.Mostrar(JPImagenCat);
            } catch (MalformedURLException ex) {
                Logger.getLogger(FrmCategoria.class.getName()).log(Level.SEVERE, null, ex);
            }
        } else {
            btnEditarCat.setEnabled(false);
            btnEliminarCat.setEnabled(false);
            btnCancelarCat.setEnabled(false);
            txtnombreCat.setEditable(true);
            JOptionPane.showMessageDialog(null, "No Existe la Categoria que desea Buscar");
        }
        btnMostrarCat.setEnabled(true);
        btnCancelarCat.setEnabled(true);
        txtnombreCat.setEditable(false);
        btnBuscarCat.setEnabled(false);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        JPImagenCat = new javax.swing.JPanel();
        btnNuevo = new javax.swing.JButton();
        btnEliminarCat = new javax.swing.JButton();
        btnMostrarCat = new javax.swing.JButton();
        btnEditarCat = new javax.swing.JButton();
        btnAgregarCat = new javax.swing.JButton();
        btnAbrirCat = new javax.swing.JButton();
        btnSalirCat = new javax.swing.JButton();
        btnCancelarCat = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnBuscarCat = new javax.swing.JButton();
        txtnombreCat = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(70, 99, 138));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("REGISTRAR CATEGORIA");

        jPanel2.setBackground(new java.awt.Color(247, 254, 255));

        JPImagenCat.setBackground(new java.awt.Color(255, 255, 255));
        JPImagenCat.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout JPImagenCatLayout = new javax.swing.GroupLayout(JPImagenCat);
        JPImagenCat.setLayout(JPImagenCatLayout);
        JPImagenCatLayout.setHorizontalGroup(
            JPImagenCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 146, Short.MAX_VALUE)
        );
        JPImagenCatLayout.setVerticalGroup(
            JPImagenCatLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 135, Short.MAX_VALUE)
        );

        btnNuevo.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnNuevo.setText("Nuevo");
        btnNuevo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNuevoActionPerformed(evt);
            }
        });

        btnEliminarCat.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnEliminarCat.setText("Eliminar");
        btnEliminarCat.setEnabled(false);
        btnEliminarCat.setMaximumSize(new java.awt.Dimension(55, 23));
        btnEliminarCat.setMinimumSize(new java.awt.Dimension(55, 23));
        btnEliminarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarCatActionPerformed(evt);
            }
        });

        btnMostrarCat.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnMostrarCat.setText("Mostrar");
        btnMostrarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnMostrarCatActionPerformed(evt);
            }
        });

        btnEditarCat.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnEditarCat.setText("Modificar");
        btnEditarCat.setEnabled(false);
        btnEditarCat.setMaximumSize(new java.awt.Dimension(55, 23));
        btnEditarCat.setMinimumSize(new java.awt.Dimension(55, 23));
        btnEditarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarCatActionPerformed(evt);
            }
        });

        btnAgregarCat.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnAgregarCat.setText("Agregar");
        btnAgregarCat.setEnabled(false);
        btnAgregarCat.setMaximumSize(new java.awt.Dimension(55, 23));
        btnAgregarCat.setMinimumSize(new java.awt.Dimension(55, 23));
        btnAgregarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarCatActionPerformed(evt);
            }
        });

        btnAbrirCat.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnAbrirCat.setText("Examinar");
        btnAbrirCat.setEnabled(false);
        btnAbrirCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAbrirCatActionPerformed(evt);
            }
        });

        btnSalirCat.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnSalirCat.setText("Salir");
        btnSalirCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirCatActionPerformed(evt);
            }
        });

        btnCancelarCat.setText("Cancelar");
        btnCancelarCat.setEnabled(false);
        btnCancelarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarCatActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12));
        jLabel1.setText("Nombre Categoria :");

        btnBuscarCat.setFont(new java.awt.Font("Tahoma", 0, 12));
        btnBuscarCat.setText("...");
        btnBuscarCat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarCatActionPerformed(evt);
            }
        });

        txtnombreCat.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtnombreCatKeyTyped(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(btnAbrirCat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(JPImagenCat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnMostrarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEditarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnNuevo, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(btnCancelarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnEliminarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(btnAgregarCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(btnSalirCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(31, 31, 31)
                        .addComponent(txtnombreCat, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnBuscarCat, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap(24, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(jLabel1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(txtnombreCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(btnBuscarCat))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(JPImagenCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnAbrirCat))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnNuevo)
                            .addComponent(btnAgregarCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnEditarCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnEliminarCat, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnMostrarCat)
                            .addComponent(btnCancelarCat))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnSalirCat)))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(155, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addContainerGap())
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 299, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAbrirCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAbrirCatActionPerformed
        // TODO add your handling code here:
        JPImagenCat.removeAll();
        met.Abrir_Dialogo(JPImagenCat);
        ImagenURL = met.ObtenerUrl(); //Aka obtengo la direccion de la Imagen Guardada en el Disco
    }//GEN-LAST:event_btnAbrirCatActionPerformed

    private void btnSalirCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirCatActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnSalirCatActionPerformed

    private void btnAgregarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarCatActionPerformed
        // TODO add your handling code here:
        Categoria cat = new Categoria() {
        };
        cat.setNomcateg(txtnombreCat.getText());
        cat.setImagen(ImagenURL);
        try {
            BDCategoria.insertarCategoria(cat);
            txtnombreCat.setText("");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
        }
        JOptionPane.showMessageDialog(null, "Se Agrego Correctamente!!");
    }//GEN-LAST:event_btnAgregarCatActionPerformed

    private void txtnombreCatKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnombreCatKeyTyped
        // TODO add your handling code here:
        if (!String.valueOf(evt.getKeyChar()).matches("[a-zA-Z]|\\s")) {
            Toolkit.getDefaultToolkit().beep();
            evt.consume();
        }
    }//GEN-LAST:event_txtnombreCatKeyTyped

    private void btnEditarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarCatActionPerformed
        // TODO add your handling code here:
        Categoria cat;
        try {
            cat = BDCategoria.buscarCategoriaNom(txtnombreCat.getText());
            cat.setImagen(ImagenURL);
            BDCategoria.actualizarCategoria(cat);
            JOptionPane.showMessageDialog(null, " [ Datos Actualizados ]");
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error BD: " + e.getMessage());
        }
    }//GEN-LAST:event_btnEditarCatActionPerformed

    private void btnBuscarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarCatActionPerformed
        // TODO add your handling code here:
        if (txtnombreCat.getText().compareTo("") != 0) {
            int result = JOptionPane.showConfirmDialog(
                    this, "Deseas Buscar para Modificar la Categoria?",
                    "Mensaje..!!",
                    JOptionPane.YES_NO_OPTION);

            if (result == JOptionPane.YES_OPTION) {
                BuscarCategoria();
                btnAbrirCat.setEnabled(true);
                btnEditarCat.setEnabled(true);
            }
            if (result == JOptionPane.NO_OPTION) {
                BuscarCategoria();
                btnEliminarCat.setEnabled(true);
            }
        } else {
            JOptionPane.showMessageDialog(null, "Ingrese Nombre que Desea Buscar");
        }
    }//GEN-LAST:event_btnBuscarCatActionPerformed

    private void btnNuevoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNuevoActionPerformed
        // TODO add your handling code here:
        txtnombreCat.setText("");
        txtnombreCat.setEditable(true);
        JPImagenCat.setEnabled(true);
        btnAgregarCat.setEnabled(true);
        btnAbrirCat.setEnabled(true);
        btnCancelarCat.setEnabled(true);
        btnNuevo.setEnabled(false);
    }//GEN-LAST:event_btnNuevoActionPerformed

    private void btnMostrarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnMostrarCatActionPerformed
        // TODO add your handling code here:
        JDListaCategorias LC = new JDListaCategorias(this, true) {};
        LC.setVisible(true);
    }//GEN-LAST:event_btnMostrarCatActionPerformed

    private void btnEliminarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarCatActionPerformed
        // TODO add your handling code here:
        try {
            Categoria cat = BDCategoria.buscarCategoriaNomCM(txtnombreCat.getText());
            if (cat == null) {
                JOptionPane.showMessageDialog(null, "No existe");
            } else {
                BDCategoria.eliminarCategoria(cat.getCodcateg());
                JOptionPane.showMessageDialog(null, "Se elimino Exitosamente");
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "ERROR: " + e.getMessage());
        }
        txtnombreCat.setText("");
        txtnombreCat.setEditable(true);
        btnBuscarCat.setEnabled(true);
        btnEliminarCat.setEnabled(false);
        btnCancelarCat.setEnabled(false);
    }//GEN-LAST:event_btnEliminarCatActionPerformed

    private void btnCancelarCatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarCatActionPerformed
        // TODO add your handling code here:
        txtnombreCat.setText("");
        txtnombreCat.setEditable(true);
        btnAgregarCat.setEnabled(false);
        btnCancelarCat.setEnabled(false);
        btnBuscarCat.setEnabled(true);
        btnNuevo.setEnabled(false);
    }//GEN-LAST:event_btnCancelarCatActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new FrmCategoria().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel JPImagenCat;
    private javax.swing.JButton btnAbrirCat;
    private javax.swing.JButton btnAgregarCat;
    private javax.swing.JButton btnBuscarCat;
    private javax.swing.JButton btnCancelarCat;
    private javax.swing.JButton btnEditarCat;
    private javax.swing.JButton btnEliminarCat;
    private javax.swing.JButton btnMostrarCat;
    private javax.swing.JButton btnNuevo;
    private javax.swing.JButton btnSalirCat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtnombreCat;
    // End of variables declaration//GEN-END:variables
}
